name: SimplePortals
main: falkirks\simpleportals\SimplePortals
author: Falkirks
version: 0.0.7
api: [1.10.0, 2.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
depend: ["SimpleWarp"]
permissions:
  simpleportals:
    default: op
    children:
      simpleportals.create:
        default: op
        description: Create a new portal
      simpleportals.use:
        default: true
        description: Use existing portals
